---
- name: configure /etc/timezone
  copy:
    content: "{{ time_zone }}"
    dest: /etc/timeszone
    owner: root
    group: root
    mode: 0644

- name: configure /etc/systemd/timesyncd.conf
  template:
    src: timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart systemd-timesyncd
  when: systemd_timesyncd

- name: start and enable timeservices
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
  - systemd-timedated
  - systemd-timesyncd
  when: systemd_timesyncd
